/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";
import {CategoryDTO} from '../model/CategoryDTO';
import {SongDTO} from '../model/SongDTO';
import {UniversalCreateDTO} from '../model/UniversalCreateDTO';

/**
* CategoryResource service.
* @module api/CategoryResourceApi
* @version 1.5.5
*/
export class CategoryResourceApi {

    /**
    * Constructs a new CategoryResourceApi. 
    * @alias module:api/CategoryResourceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createCategoryUsingPOST operation.
     * @callback module:api/CategoryResourceApi~createCategoryUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createCategory
     * @param {module:model/UniversalCreateDTO} categoryDto categoryDto
     * @param {module:api/CategoryResourceApi~createCategoryUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryDTO}
     */
    createCategoryUsingPOST(categoryDto, callback) {
      let postBody = categoryDto;

      // verify the required parameter 'categoryDto' is set
      if (categoryDto === undefined || categoryDto === null) {
        throw new Error("Missing the required parameter 'categoryDto' when calling createCategoryUsingPOST");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = CategoryDTO;

      return this.apiClient.callApi(
        '/api/categories', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteCategoryUsingDELETE operation.
     * @callback module:api/CategoryResourceApi~deleteCategoryUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deleteCategory
     * @param {Number} id id
     * @param {module:api/CategoryResourceApi~deleteCategoryUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteCategoryUsingDELETE(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteCategoryUsingDELETE");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/categories/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllCategoriesUsingGET operation.
     * @callback module:api/CategoryResourceApi~getAllCategoriesUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CategoryDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllCategories
     * @param {module:api/CategoryResourceApi~getAllCategoriesUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CategoryDTO>}
     */
    getAllCategoriesUsingGET(callback) {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [CategoryDTO];

      return this.apiClient.callApi(
        '/api/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getCategoryByIdUsingGET operation.
     * @callback module:api/CategoryResourceApi~getCategoryByIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getCategoryById
     * @param {Number} id id
     * @param {module:api/CategoryResourceApi~getCategoryByIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryDTO}
     */
    getCategoryByIdUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCategoryByIdUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = CategoryDTO;

      return this.apiClient.callApi(
        '/api/categories/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getCategoryByNameUsingGET operation.
     * @callback module:api/CategoryResourceApi~getCategoryByNameUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CategoryDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getCategoryByName
     * @param {String} name name
     * @param {module:api/CategoryResourceApi~getCategoryByNameUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CategoryDTO>}
     */
    getCategoryByNameUsingGET(name, callback) {
      let postBody = null;

      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getCategoryByNameUsingGET");
      }


      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [CategoryDTO];

      return this.apiClient.callApi(
        '/api/categories/name/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsByCategoryIdUsingGET operation.
     * @callback module:api/CategoryResourceApi~getSongsByCategoryIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getSongsByCategoryId
     * @param {Number} id id
     * @param {module:api/CategoryResourceApi~getSongsByCategoryIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongDTO>}
     */
    getSongsByCategoryIdUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsByCategoryIdUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [SongDTO];

      return this.apiClient.callApi(
        '/api/categories/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCategoryUsingPUT operation.
     * @callback module:api/CategoryResourceApi~updateCategoryUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CategoryDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateCategory
     * @param {module:model/CategoryDTO} categoryDto categoryDto
     * @param {module:api/CategoryResourceApi~updateCategoryUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CategoryDTO}
     */
    updateCategoryUsingPUT(categoryDto, callback) {
      let postBody = categoryDto;

      // verify the required parameter 'categoryDto' is set
      if (categoryDto === undefined || categoryDto === null) {
        throw new Error("Missing the required parameter 'categoryDto' when calling updateCategoryUsingPUT");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = CategoryDTO;

      return this.apiClient.callApi(
        '/api/categories', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
