/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";
import {SongCoauthorDTO} from '../model/SongCoauthorDTO';

/**
* SongCoauthorResource service.
* @module api/SongCoauthorResourceApi
* @version 1.5.5
*/
export class SongCoauthorResourceApi {

    /**
    * Constructs a new SongCoauthorResourceApi. 
    * @alias module:api/SongCoauthorResourceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createUsingPOST3 operation.
     * @callback module:api/SongCoauthorResourceApi~createUsingPOST3Callback
     * @param {String} error Error message, if any.
     * @param {module:model/SongCoauthorDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create
     * @param {module:model/SongCoauthorDTO} songCoauthorDTO songCoauthorDTO
     * @param {module:api/SongCoauthorResourceApi~createUsingPOST3Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongCoauthorDTO}
     */
    createUsingPOST3(songCoauthorDTO, callback) {
      let postBody = songCoauthorDTO;

      // verify the required parameter 'songCoauthorDTO' is set
      if (songCoauthorDTO === undefined || songCoauthorDTO === null) {
        throw new Error("Missing the required parameter 'songCoauthorDTO' when calling createUsingPOST3");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = SongCoauthorDTO;

      return this.apiClient.callApi(
        '/api/coauthors', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUsingDELETE3 operation.
     * @callback module:api/SongCoauthorResourceApi~deleteUsingDELETE3Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete
     * @param {Number} authorId authorId
     * @param {String} _function function
     * @param {Number} songId songId
     * @param {module:api/SongCoauthorResourceApi~deleteUsingDELETE3Callback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUsingDELETE3(authorId, _function, songId, callback) {
      let postBody = null;

      // verify the required parameter 'authorId' is set
      if (authorId === undefined || authorId === null) {
        throw new Error("Missing the required parameter 'authorId' when calling deleteUsingDELETE3");
      }

      // verify the required parameter '_function' is set
      if (_function === undefined || _function === null) {
        throw new Error("Missing the required parameter '_function' when calling deleteUsingDELETE3");
      }

      // verify the required parameter 'songId' is set
      if (songId === undefined || songId === null) {
        throw new Error("Missing the required parameter 'songId' when calling deleteUsingDELETE3");
      }


      let pathParams = {
        'authorId': authorId,
        'function': _function,
        'songId': songId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/coauthors/{songId}/{authorId}/{function}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getByAuthorIdUsingGET operation.
     * @callback module:api/SongCoauthorResourceApi~getByAuthorIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongCoauthorDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getByAuthorId
     * @param {Number} id id
     * @param {module:api/SongCoauthorResourceApi~getByAuthorIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongCoauthorDTO>}
     */
    getByAuthorIdUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getByAuthorIdUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [SongCoauthorDTO];

      return this.apiClient.callApi(
        '/api/coauthors/author/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getByFunctionUsingGET operation.
     * @callback module:api/SongCoauthorResourceApi~getByFunctionUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongCoauthorDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getByFunction
     * @param {module:model/String} _function function
     * @param {module:api/SongCoauthorResourceApi~getByFunctionUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongCoauthorDTO>}
     */
    getByFunctionUsingGET(_function, callback) {
      let postBody = null;

      // verify the required parameter '_function' is set
      if (_function === undefined || _function === null) {
        throw new Error("Missing the required parameter '_function' when calling getByFunctionUsingGET");
      }


      let pathParams = {
        'function': _function
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [SongCoauthorDTO];

      return this.apiClient.callApi(
        '/api/coauthors/function/{function}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getBySongIdUsingGET operation.
     * @callback module:api/SongCoauthorResourceApi~getBySongIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongCoauthorDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getBySongId
     * @param {Number} id id
     * @param {module:api/SongCoauthorResourceApi~getBySongIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongCoauthorDTO>}
     */
    getBySongIdUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getBySongIdUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [SongCoauthorDTO];

      return this.apiClient.callApi(
        '/api/coauthors/song/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUsingPUT3 operation.
     * @callback module:api/SongCoauthorResourceApi~updateUsingPUT3Callback
     * @param {String} error Error message, if any.
     * @param {module:model/SongCoauthorDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update
     * @param {module:model/SongCoauthorDTO} songCoauthorDTO songCoauthorDTO
     * @param {module:api/SongCoauthorResourceApi~updateUsingPUT3Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SongCoauthorDTO}
     */
    updateUsingPUT3(songCoauthorDTO, callback) {
      let postBody = songCoauthorDTO;

      // verify the required parameter 'songCoauthorDTO' is set
      if (songCoauthorDTO === undefined || songCoauthorDTO === null) {
        throw new Error("Missing the required parameter 'songCoauthorDTO' when calling updateUsingPUT3");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = SongCoauthorDTO;

      return this.apiClient.callApi(
        '/api/coauthors', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
