/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";
import {SongDTO} from '../model/SongDTO';
import {TagDTO} from '../model/TagDTO';
import {UniversalCreateDTO} from '../model/UniversalCreateDTO';

/**
* TagResource service.
* @module api/TagResourceApi
* @version 1.5.5
*/
export class TagResourceApi {

    /**
    * Constructs a new TagResourceApi. 
    * @alias module:api/TagResourceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTagUsingPOST operation.
     * @callback module:api/TagResourceApi~createTagUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TagDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createTag
     * @param {module:model/UniversalCreateDTO} tagDto tagDto
     * @param {module:api/TagResourceApi~createTagUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TagDTO}
     */
    createTagUsingPOST(tagDto, callback) {
      let postBody = tagDto;

      // verify the required parameter 'tagDto' is set
      if (tagDto === undefined || tagDto === null) {
        throw new Error("Missing the required parameter 'tagDto' when calling createTagUsingPOST");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = TagDTO;

      return this.apiClient.callApi(
        '/api/tags', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTagUsingDELETE operation.
     * @callback module:api/TagResourceApi~deleteTagUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deleteTag
     * @param {Number} id id
     * @param {module:api/TagResourceApi~deleteTagUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTagUsingDELETE(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteTagUsingDELETE");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/tags/id/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllTagsUsingGET operation.
     * @callback module:api/TagResourceApi~getAllTagsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TagDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllTags
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit limit
     * @param {module:api/TagResourceApi~getAllTagsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TagDTO>}
     */
    getAllTagsUsingGET(opts, callback) {
      opts = opts || {};
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [TagDTO];

      return this.apiClient.callApi(
        '/api/tags', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSongsByTagUsingGET operation.
     * @callback module:api/TagResourceApi~getSongsByTagUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SongDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getSongsByTag
     * @param {Number} id id
     * @param {module:api/TagResourceApi~getSongsByTagUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SongDTO>}
     */
    getSongsByTagUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSongsByTagUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [SongDTO];

      return this.apiClient.callApi(
        '/api/tags/{id}/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTagByIdUsingGET operation.
     * @callback module:api/TagResourceApi~getTagByIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TagDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getTagById
     * @param {Number} id id
     * @param {module:api/TagResourceApi~getTagByIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TagDTO}
     */
    getTagByIdUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTagByIdUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = TagDTO;

      return this.apiClient.callApi(
        '/api/tags/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTagByNameUsingGET operation.
     * @callback module:api/TagResourceApi~getTagByNameUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TagDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getTagByName
     * @param {String} name name
     * @param {module:api/TagResourceApi~getTagByNameUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TagDTO>}
     */
    getTagByNameUsingGET(name, callback) {
      let postBody = null;

      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getTagByNameUsingGET");
      }


      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [TagDTO];

      return this.apiClient.callApi(
        '/api/tags/name/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTagUsingPUT operation.
     * @callback module:api/TagResourceApi~updateTagUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TagDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateTag
     * @param {module:model/TagDTO} tagDto tagDto
     * @param {module:api/TagResourceApi~updateTagUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TagDTO}
     */
    updateTagUsingPUT(tagDto, callback) {
      let postBody = tagDto;

      // verify the required parameter 'tagDto' is set
      if (tagDto === undefined || tagDto === null) {
        throw new Error("Missing the required parameter 'tagDto' when calling updateTagUsingPUT");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = TagDTO;

      return this.apiClient.callApi(
        '/api/tags', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
