/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";
import {UniversalCreateDTO} from '../model/UniversalCreateDTO';
import {UserDTO} from '../model/UserDTO';
import {UserRoleDTO} from '../model/UserRoleDTO';

/**
* UserRoleResource service.
* @module api/UserRoleResourceApi
* @version 1.5.5
*/
export class UserRoleResourceApi {

    /**
    * Constructs a new UserRoleResourceApi. 
    * @alias module:api/UserRoleResourceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createUsingPOST6 operation.
     * @callback module:api/UserRoleResourceApi~createUsingPOST6Callback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRoleDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create
     * @param {module:model/UniversalCreateDTO} userRoleDto userRoleDto
     * @param {module:api/UserRoleResourceApi~createUsingPOST6Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRoleDTO}
     */
    createUsingPOST6(userRoleDto, callback) {
      let postBody = userRoleDto;

      // verify the required parameter 'userRoleDto' is set
      if (userRoleDto === undefined || userRoleDto === null) {
        throw new Error("Missing the required parameter 'userRoleDto' when calling createUsingPOST6");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = UserRoleDTO;

      return this.apiClient.callApi(
        '/api/user_roles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUsingDELETE7 operation.
     * @callback module:api/UserRoleResourceApi~deleteUsingDELETE7Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete
     * @param {Number} id id
     * @param {module:api/UserRoleResourceApi~deleteUsingDELETE7Callback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUsingDELETE7(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUsingDELETE7");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/user_roles/id/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllUsingGET7 operation.
     * @callback module:api/UserRoleResourceApi~getAllUsingGET7Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/UserRoleDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAll
     * @param {module:api/UserRoleResourceApi~getAllUsingGET7Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/UserRoleDTO>}
     */
    getAllUsingGET7(callback) {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [UserRoleDTO];

      return this.apiClient.callApi(
        '/api/user_roles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getByIdUsingGET7 operation.
     * @callback module:api/UserRoleResourceApi~getByIdUsingGET7Callback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRoleDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getById
     * @param {Number} id id
     * @param {module:api/UserRoleResourceApi~getByIdUsingGET7Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRoleDTO}
     */
    getByIdUsingGET7(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getByIdUsingGET7");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UserRoleDTO;

      return this.apiClient.callApi(
        '/api/user_roles/id/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getByNameSearchQueryUsingGET operation.
     * @callback module:api/UserRoleResourceApi~getByNameSearchQueryUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/UserRoleDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getByNameSearchQuery
     * @param {String} searchQuery searchQuery
     * @param {module:api/UserRoleResourceApi~getByNameSearchQueryUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/UserRoleDTO>}
     */
    getByNameSearchQueryUsingGET(searchQuery, callback) {
      let postBody = null;

      // verify the required parameter 'searchQuery' is set
      if (searchQuery === undefined || searchQuery === null) {
        throw new Error("Missing the required parameter 'searchQuery' when calling getByNameSearchQueryUsingGET");
      }


      let pathParams = {
        'searchQuery': searchQuery
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [UserRoleDTO];

      return this.apiClient.callApi(
        '/api/user_roles/name/{searchQuery}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsersByUserRoleIdUsingGET operation.
     * @callback module:api/UserRoleResourceApi~getUsersByUserRoleIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/UserDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getUsersByUserRoleId
     * @param {Number} id id
     * @param {module:api/UserRoleResourceApi~getUsersByUserRoleIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/UserDTO>}
     */
    getUsersByUserRoleIdUsingGET(id, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getUsersByUserRoleIdUsingGET");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [UserDTO];

      return this.apiClient.callApi(
        '/api/user_roles/id/{id}/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUsingPUT6 operation.
     * @callback module:api/UserRoleResourceApi~updateUsingPUT6Callback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRoleDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update
     * @param {module:model/UserRoleDTO} userRoleDto userRoleDto
     * @param {module:api/UserRoleResourceApi~updateUsingPUT6Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRoleDTO}
     */
    updateUsingPUT6(userRoleDto, callback) {
      let postBody = userRoleDto;

      // verify the required parameter 'userRoleDto' is set
      if (userRoleDto === undefined || userRoleDto === null) {
        throw new Error("Missing the required parameter 'userRoleDto' when calling updateUsingPUT6");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = UserRoleDTO;

      return this.apiClient.callApi(
        '/api/user_roles', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
