/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SongbookApi);
  }
}(this, function(expect, SongbookApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateSongDTO', function() {
      beforeEach(function() {
        instance = new SongbookApi.CreateSongDTO();
      });

      it('should create an instance of CreateSongDTO', function() {
        // TODO: update the code to test CreateSongDTO
        expect(instance).to.be.a(SongbookApi.CreateSongDTO);
      });

      it('should have the property authorName (base name: "authorName")', function() {
        // TODO: update the code to test the property authorName
        expect(instance).to.have.property('authorName');
        // expect(instance.authorName).to.be(expectedValueLiteral);
      });

      it('should have the property categoryId (base name: "categoryId")', function() {
        // TODO: update the code to test the property categoryId
        expect(instance).to.have.property('categoryId');
        // expect(instance.categoryId).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property coauthors (base name: "coauthors")', function() {
        // TODO: update the code to test the property coauthors
        expect(instance).to.have.property('coauthors');
        // expect(instance.coauthors).to.be(expectedValueLiteral);
      });

      it('should have the property lyrics (base name: "lyrics")', function() {
        // TODO: update the code to test the property lyrics
        expect(instance).to.have.property('lyrics');
        // expect(instance.lyrics).to.be(expectedValueLiteral);
      });

      it('should have the property guitarTabs (base name: "guitarTabs")', function() {
        // TODO: update the code to test the property guitarTabs
        expect(instance).to.have.property('guitarTabs');
        // expect(instance.guitarTabs).to.be(expectedValueLiteral);
      });

      it('should have the property trivia (base name: "trivia")', function() {
        // TODO: update the code to test the property trivia
        expect(instance).to.have.property('trivia');
        // expect(instance.trivia).to.be(expectedValueLiteral);
      });

      it('should have the property tags (base name: "tags")', function() {
        // TODO: update the code to test the property tags
        expect(instance).to.have.property('tags');
        // expect(instance.tags).to.be(expectedValueLiteral);
      });

    });
  });

}));
