/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SongbookApi);
  }
}(this, function(expect, SongbookApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SongAddDTO', function() {
      beforeEach(function() {
        instance = new SongbookApi.SongAddDTO();
      });

      it('should create an instance of SongAddDTO', function() {
        // TODO: update the code to test SongAddDTO
        expect(instance).to.be.a(SongbookApi.SongAddDTO);
      });

      it('should have the property addedBy (base name: "addedBy")', function() {
        // TODO: update the code to test the property addedBy
        expect(instance).to.have.property('addedBy');
        // expect(instance.addedBy).to.be(expectedValueLiteral);
      });

      it('should have the property addedSong (base name: "addedSong")', function() {
        // TODO: update the code to test the property addedSong
        expect(instance).to.have.property('addedSong');
        // expect(instance.addedSong).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

    });
  });

}));
