/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {URL} from './URL';

/**
 * The AuthorDTO model module.
 * @module model/AuthorDTO
 * @version 1.5.5
 */
export class AuthorDTO {
  /**
   * Constructs a new <code>AuthorDTO</code>.
   * @alias module:model/AuthorDTO
   * @class
   * @param id {Number} 
   * @param name {String} 
   */
  constructor(id, name) {
    this.id = id;
    this.name = name;
  }

  /**
   * Constructs a <code>AuthorDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthorDTO} obj Optional instance to populate.
   * @return {module:model/AuthorDTO} The populated <code>AuthorDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthorDTO();
      if (data.hasOwnProperty('biographyUrl'))
        obj.biographyUrl = URL.constructFromObject(data['biographyUrl']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('photoResource'))
        obj.photoResource = ApiClient.convertToType(data['photoResource'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/URL} biographyUrl
 */
AuthorDTO.prototype.biographyUrl = undefined;

/**
 * @member {Number} id
 */
AuthorDTO.prototype.id = undefined;

/**
 * @member {String} name
 */
AuthorDTO.prototype.name = undefined;

/**
 * @member {String} photoResource
 */
AuthorDTO.prototype.photoResource = undefined;


