/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The CreateCoauthorDTO model module.
 * @module model/CreateCoauthorDTO
 * @version 1.5.5
 */
export class CreateCoauthorDTO {
  /**
   * Constructs a new <code>CreateCoauthorDTO</code>.
   * @alias module:model/CreateCoauthorDTO
   * @class
   * @param coauthorFunction {module:model/CreateCoauthorDTO.CoauthorFunctionEnum} 
   */
  constructor(coauthorFunction) {
    this.coauthorFunction = coauthorFunction;
  }

  /**
   * Constructs a <code>CreateCoauthorDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCoauthorDTO} obj Optional instance to populate.
   * @return {module:model/CreateCoauthorDTO} The populated <code>CreateCoauthorDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateCoauthorDTO();
      if (data.hasOwnProperty('authorName'))
        obj.authorName = ApiClient.convertToType(data['authorName'], 'String');
      if (data.hasOwnProperty('coauthorFunction'))
        obj.coauthorFunction = ApiClient.convertToType(data['coauthorFunction'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} authorName
 */
CreateCoauthorDTO.prototype.authorName = undefined;

/**
 * Allowed values for the <code>coauthorFunction</code> property.
 * @enum {String}
 * @readonly
 */
CreateCoauthorDTO.CoauthorFunctionEnum = {
  /**
   * value: "MUSIC"
   * @const
   */
  MUSIC: "MUSIC",

  /**
   * value: "TEXT"
   * @const
   */
  TEXT: "TEXT"
};

/**
 * @member {module:model/CreateCoauthorDTO.CoauthorFunctionEnum} coauthorFunction
 */
CreateCoauthorDTO.prototype.coauthorFunction = undefined;


