/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The CreatePlaylistDTO model module.
 * @module model/CreatePlaylistDTO
 * @version 1.5.5
 */
export class CreatePlaylistDTO {
  /**
   * Constructs a new <code>CreatePlaylistDTO</code>.
   * @alias module:model/CreatePlaylistDTO
   * @class
   * @param isPrivate {Boolean} 
   * @param ownerId {Number} 
   * @param songs {Array.<Number>} 
   */
  constructor(isPrivate, ownerId, songs) {
    this.isPrivate = isPrivate;
    this.ownerId = ownerId;
    this.songs = songs;
  }

  /**
   * Constructs a <code>CreatePlaylistDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreatePlaylistDTO} obj Optional instance to populate.
   * @return {module:model/CreatePlaylistDTO} The populated <code>CreatePlaylistDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreatePlaylistDTO();
      if (data.hasOwnProperty('isPrivate'))
        obj.isPrivate = ApiClient.convertToType(data['isPrivate'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'Number');
      if (data.hasOwnProperty('songs'))
        obj.songs = ApiClient.convertToType(data['songs'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} isPrivate
 */
CreatePlaylistDTO.prototype.isPrivate = undefined;

/**
 * @member {String} name
 */
CreatePlaylistDTO.prototype.name = undefined;

/**
 * @member {Number} ownerId
 */
CreatePlaylistDTO.prototype.ownerId = undefined;

/**
 * @member {Array.<Number>} songs
 */
CreatePlaylistDTO.prototype.songs = undefined;


