/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The CreateGuitarCordDTO model module.
 * @module model/CreateGuitarCordDTO
 * @version 1.5.5
 */
export class CreateGuitarCordDTO {
  /**
   * Constructs a new <code>CreateGuitarCordDTO</code>.
   * Class representing a DTO for creating guitar cords for lines of the songs.
   * @alias module:model/CreateGuitarCordDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateGuitarCordDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateGuitarCordDTO} obj Optional instance to populate.
   * @return {module:model/CreateGuitarCordDTO} The populated <code>CreateGuitarCordDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateGuitarCordDTO();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('position'))
        obj.position = ApiClient.convertToType(data['position'], 'Number');
    }
    return obj;
  }
}

/**
 * Content of the cord in the song
 * @member {String} content
 */
CreateGuitarCordDTO.prototype.content = undefined;

/**
 * Position in the line of the cord.
 * @member {Number} position
 */
CreateGuitarCordDTO.prototype.position = undefined;


