/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The InputStream model module.
 * @module model/InputStream
 * @version 1.5.5
 */
export class InputStream {
  /**
   * Constructs a new <code>InputStream</code>.
   * @alias module:model/InputStream
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InputStream</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InputStream} obj Optional instance to populate.
   * @return {module:model/InputStream} The populated <code>InputStream</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InputStream();
    }
    return obj;
  }
}

