/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The LineDTO model module.
 * @module model/LineDTO
 * @version 1.5.5
 */
export class LineDTO {
  /**
   * Constructs a new <code>LineDTO</code>.
   * @alias module:model/LineDTO
   * @class
   * @param content {String} 
   * @param id {Number} 
   * @param order {Number} 
   */
  constructor(content, id, order) {
    this.content = content;
    this.id = id;
    this.order = order;
  }

  /**
   * Constructs a <code>LineDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LineDTO} obj Optional instance to populate.
   * @return {module:model/LineDTO} The populated <code>LineDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LineDTO();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} content
 */
LineDTO.prototype.content = undefined;

/**
 * @member {Number} id
 */
LineDTO.prototype.id = undefined;

/**
 * @member {Number} order
 */
LineDTO.prototype.order = undefined;


