/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The PlaylistDTO model module.
 * @module model/PlaylistDTO
 * @version 1.5.5
 */
export class PlaylistDTO {
  /**
   * Constructs a new <code>PlaylistDTO</code>.
   * @alias module:model/PlaylistDTO
   * @class
   * @param id {Number} 
   * @param isPrivate {Boolean} 
   * @param name {String} 
   * @param ownerId {Number} 
   * @param songs {Array.<Number>} 
   */
  constructor(id, isPrivate, name, ownerId, songs) {
    this.id = id;
    this.isPrivate = isPrivate;
    this.name = name;
    this.ownerId = ownerId;
    this.songs = songs;
  }

  /**
   * Constructs a <code>PlaylistDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PlaylistDTO} obj Optional instance to populate.
   * @return {module:model/PlaylistDTO} The populated <code>PlaylistDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PlaylistDTO();
      if (data.hasOwnProperty('creationTime'))
        obj.creationTime = ApiClient.convertToType(data['creationTime'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('isPrivate'))
        obj.isPrivate = ApiClient.convertToType(data['isPrivate'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'Number');
      if (data.hasOwnProperty('songs'))
        obj.songs = ApiClient.convertToType(data['songs'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Date} creationTime
 */
PlaylistDTO.prototype.creationTime = undefined;

/**
 * @member {Number} id
 */
PlaylistDTO.prototype.id = undefined;

/**
 * @member {Boolean} isPrivate
 */
PlaylistDTO.prototype.isPrivate = undefined;

/**
 * @member {String} name
 */
PlaylistDTO.prototype.name = undefined;

/**
 * @member {Number} ownerId
 */
PlaylistDTO.prototype.ownerId = undefined;

/**
 * @member {Array.<Number>} songs
 */
PlaylistDTO.prototype.songs = undefined;


