/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The SongEditDTO model module.
 * @module model/SongEditDTO
 * @version 1.5.5
 */
export class SongEditDTO {
  /**
   * Constructs a new <code>SongEditDTO</code>.
   * @alias module:model/SongEditDTO
   * @class
   * @param editedBy {Number} 
   * @param editedSong {Number} 
   * @param id {Number} 
   */
  constructor(editedBy, editedSong, id) {
    this.editedBy = editedBy;
    this.editedSong = editedSong;
    this.id = id;
  }

  /**
   * Constructs a <code>SongEditDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SongEditDTO} obj Optional instance to populate.
   * @return {module:model/SongEditDTO} The populated <code>SongEditDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SongEditDTO();
      if (data.hasOwnProperty('editedBy'))
        obj.editedBy = ApiClient.convertToType(data['editedBy'], 'Number');
      if (data.hasOwnProperty('editedSong'))
        obj.editedSong = ApiClient.convertToType(data['editedSong'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} editedBy
 */
SongEditDTO.prototype.editedBy = undefined;

/**
 * @member {Number} editedSong
 */
SongEditDTO.prototype.editedSong = undefined;

/**
 * @member {Number} id
 */
SongEditDTO.prototype.id = undefined;

/**
 * @member {Date} timestamp
 */
SongEditDTO.prototype.timestamp = undefined;


