/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {AuthorDTO} from './AuthorDTO';
import {CategoryDTO} from './CategoryDTO';
import {SongAddDTO} from './SongAddDTO';
import {SongCoauthorDTO} from './SongCoauthorDTO';
import {SongEditDTO} from './SongEditDTO';
import {TagDTO} from './TagDTO';

/**
 * The SongDTO model module.
 * @module model/SongDTO
 * @version 1.5.5
 */
export class SongDTO {
  /**
   * Constructs a new <code>SongDTO</code>.
   * @alias module:model/SongDTO
   * @class
   * @param coauthors {Array.<module:model/SongCoauthorDTO>} 
   * @param edits {Array.<module:model/SongEditDTO>} 
   * @param id {Number} 
   * @param tags {Array.<module:model/TagDTO>} 
   * @param title {String} 
   */
  constructor(coauthors, edits, id, tags, title) {
    this.coauthors = coauthors;
    this.edits = edits;
    this.id = id;
    this.tags = tags;
    this.title = title;
  }

  /**
   * Constructs a <code>SongDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SongDTO} obj Optional instance to populate.
   * @return {module:model/SongDTO} The populated <code>SongDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SongDTO();
      if (data.hasOwnProperty('addedBy'))
        obj.addedBy = SongAddDTO.constructFromObject(data['addedBy']);
      if (data.hasOwnProperty('author'))
        obj.author = AuthorDTO.constructFromObject(data['author']);
      if (data.hasOwnProperty('averageRating'))
        obj.averageRating = ApiClient.convertToType(data['averageRating'], 'Number');
      if (data.hasOwnProperty('category'))
        obj.category = CategoryDTO.constructFromObject(data['category']);
      if (data.hasOwnProperty('coauthors'))
        obj.coauthors = ApiClient.convertToType(data['coauthors'], [SongCoauthorDTO]);
      if (data.hasOwnProperty('edits'))
        obj.edits = ApiClient.convertToType(data['edits'], [SongEditDTO]);
      if (data.hasOwnProperty('guitarTabs'))
        obj.guitarTabs = ApiClient.convertToType(data['guitarTabs'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('isAwaiting'))
        obj.isAwaiting = ApiClient.convertToType(data['isAwaiting'], 'Boolean');
      if (data.hasOwnProperty('lyrics'))
        obj.lyrics = ApiClient.convertToType(data['lyrics'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], [TagDTO]);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('trivia'))
        obj.trivia = ApiClient.convertToType(data['trivia'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/SongAddDTO} addedBy
 */
SongDTO.prototype.addedBy = undefined;

/**
 * @member {module:model/AuthorDTO} author
 */
SongDTO.prototype.author = undefined;

/**
 * @member {Number} averageRating
 */
SongDTO.prototype.averageRating = undefined;

/**
 * @member {module:model/CategoryDTO} category
 */
SongDTO.prototype.category = undefined;

/**
 * @member {Array.<module:model/SongCoauthorDTO>} coauthors
 */
SongDTO.prototype.coauthors = undefined;

/**
 * @member {Array.<module:model/SongEditDTO>} edits
 */
SongDTO.prototype.edits = undefined;

/**
 * @member {String} guitarTabs
 */
SongDTO.prototype.guitarTabs = undefined;

/**
 * @member {Number} id
 */
SongDTO.prototype.id = undefined;

/**
 * @member {Boolean} isAwaiting
 */
SongDTO.prototype.isAwaiting = undefined;

/**
 * @member {String} lyrics
 */
SongDTO.prototype.lyrics = undefined;

/**
 * @member {Array.<module:model/TagDTO>} tags
 */
SongDTO.prototype.tags = undefined;

/**
 * @member {String} title
 */
SongDTO.prototype.title = undefined;

/**
 * @member {String} trivia
 */
SongDTO.prototype.trivia = undefined;


