/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SongbookApi) {
      root.SongbookApi = {};
    }
    root.SongbookApi.SongCoauthorDTO = factory(root.SongbookApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SongCoauthorDTO model module.
   * @module model/SongCoauthorDTO
   * @version 1.5.5
   */

  /**
   * Constructs a new <code>SongCoauthorDTO</code>.
   * @alias module:model/SongCoauthorDTO
   * @class
   * @param authorId {Number} 
   * @param coauthorFunction {module:model/SongCoauthorDTO.CoauthorFunctionEnum} 
   * @param songId {Number} 
   */
  var exports = function(authorId, coauthorFunction, songId) {
    this.authorId = authorId;
    this.coauthorFunction = coauthorFunction;
    this.songId = songId;
  };

  /**
   * Constructs a <code>SongCoauthorDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SongCoauthorDTO} obj Optional instance to populate.
   * @return {module:model/SongCoauthorDTO} The populated <code>SongCoauthorDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('authorId'))
        obj.authorId = ApiClient.convertToType(data['authorId'], 'Number');
      if (data.hasOwnProperty('coauthorFunction'))
        obj.coauthorFunction = ApiClient.convertToType(data['coauthorFunction'], 'String');
      if (data.hasOwnProperty('songId'))
        obj.songId = ApiClient.convertToType(data['songId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} authorId
   */
  exports.prototype.authorId = undefined;

  /**
   * @member {module:model/SongCoauthorDTO.CoauthorFunctionEnum} coauthorFunction
   */
  exports.prototype.coauthorFunction = undefined;

  /**
   * @member {Number} songId
   */
  exports.prototype.songId = undefined;


  /**
   * Allowed values for the <code>coauthorFunction</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CoauthorFunctionEnum = {
    /**
     * value: "MUSIC"
     * @const
     */
    MUSIC: "MUSIC",

    /**
     * value: "TEXT"
     * @const
     */
    TEXT: "TEXT"
  };

  return exports;

}));
