/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The SongDTO model module.
 * @module model/SongDTO
 * @version 1.5.5
 */
export class SongDTO {
  /**
   * Constructs a new <code>SongDTO</code>.
   * @alias module:model/SongDTO
   * @class
   * @param authorId {Number} 
   * @param categoryId {Number} 
   * @param id {Number} 
   * @param title {String} 
   */
  constructor(authorId, categoryId, id, title) {
    this.authorId = authorId;
    this.categoryId = categoryId;
    this.id = id;
    this.title = title;
  }

  /**
   * Constructs a <code>SongDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SongDTO} obj Optional instance to populate.
   * @return {module:model/SongDTO} The populated <code>SongDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SongDTO();
      if (data.hasOwnProperty('addedBy'))
        obj.addedBy = ApiClient.convertToType(data['addedBy'], 'Number');
      if (data.hasOwnProperty('authorId'))
        obj.authorId = ApiClient.convertToType(data['authorId'], 'Number');
      if (data.hasOwnProperty('averageRating'))
        obj.averageRating = ApiClient.convertToType(data['averageRating'], 'Number');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('isAwaiting'))
        obj.isAwaiting = ApiClient.convertToType(data['isAwaiting'], 'Boolean');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('trivia'))
        obj.trivia = ApiClient.convertToType(data['trivia'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} addedBy
 */
SongDTO.prototype.addedBy = undefined;

/**
 * @member {Number} authorId
 */
SongDTO.prototype.authorId = undefined;

/**
 * @member {Number} averageRating
 */
SongDTO.prototype.averageRating = undefined;

/**
 * @member {Number} categoryId
 */
SongDTO.prototype.categoryId = undefined;

/**
 * @member {Number} id
 */
SongDTO.prototype.id = undefined;

/**
 * @member {Boolean} isAwaiting
 */
SongDTO.prototype.isAwaiting = undefined;

/**
 * @member {String} title
 */
SongDTO.prototype.title = undefined;

/**
 * @member {String} trivia
 */
SongDTO.prototype.trivia = undefined;


