/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The URI model module.
 * @module model/URI
 * @version 1.5.5
 */
export class URI {
  /**
   * Constructs a new <code>URI</code>.
   * @alias module:model/URI
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>URI</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/URI} obj Optional instance to populate.
   * @return {module:model/URI} The populated <code>URI</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new URI();
      if (data.hasOwnProperty('absolute'))
        obj.absolute = ApiClient.convertToType(data['absolute'], 'Boolean');
      if (data.hasOwnProperty('authority'))
        obj.authority = ApiClient.convertToType(data['authority'], 'String');
      if (data.hasOwnProperty('fragment'))
        obj.fragment = ApiClient.convertToType(data['fragment'], 'String');
      if (data.hasOwnProperty('host'))
        obj.host = ApiClient.convertToType(data['host'], 'String');
      if (data.hasOwnProperty('opaque'))
        obj.opaque = ApiClient.convertToType(data['opaque'], 'Boolean');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('port'))
        obj.port = ApiClient.convertToType(data['port'], 'Number');
      if (data.hasOwnProperty('query'))
        obj.query = ApiClient.convertToType(data['query'], 'String');
      if (data.hasOwnProperty('rawAuthority'))
        obj.rawAuthority = ApiClient.convertToType(data['rawAuthority'], 'String');
      if (data.hasOwnProperty('rawFragment'))
        obj.rawFragment = ApiClient.convertToType(data['rawFragment'], 'String');
      if (data.hasOwnProperty('rawPath'))
        obj.rawPath = ApiClient.convertToType(data['rawPath'], 'String');
      if (data.hasOwnProperty('rawQuery'))
        obj.rawQuery = ApiClient.convertToType(data['rawQuery'], 'String');
      if (data.hasOwnProperty('rawSchemeSpecificPart'))
        obj.rawSchemeSpecificPart = ApiClient.convertToType(data['rawSchemeSpecificPart'], 'String');
      if (data.hasOwnProperty('rawUserInfo'))
        obj.rawUserInfo = ApiClient.convertToType(data['rawUserInfo'], 'String');
      if (data.hasOwnProperty('scheme'))
        obj.scheme = ApiClient.convertToType(data['scheme'], 'String');
      if (data.hasOwnProperty('schemeSpecificPart'))
        obj.schemeSpecificPart = ApiClient.convertToType(data['schemeSpecificPart'], 'String');
      if (data.hasOwnProperty('userInfo'))
        obj.userInfo = ApiClient.convertToType(data['userInfo'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} absolute
 */
URI.prototype.absolute = undefined;

/**
 * @member {String} authority
 */
URI.prototype.authority = undefined;

/**
 * @member {String} fragment
 */
URI.prototype.fragment = undefined;

/**
 * @member {String} host
 */
URI.prototype.host = undefined;

/**
 * @member {Boolean} opaque
 */
URI.prototype.opaque = undefined;

/**
 * @member {String} path
 */
URI.prototype.path = undefined;

/**
 * @member {Number} port
 */
URI.prototype.port = undefined;

/**
 * @member {String} query
 */
URI.prototype.query = undefined;

/**
 * @member {String} rawAuthority
 */
URI.prototype.rawAuthority = undefined;

/**
 * @member {String} rawFragment
 */
URI.prototype.rawFragment = undefined;

/**
 * @member {String} rawPath
 */
URI.prototype.rawPath = undefined;

/**
 * @member {String} rawQuery
 */
URI.prototype.rawQuery = undefined;

/**
 * @member {String} rawSchemeSpecificPart
 */
URI.prototype.rawSchemeSpecificPart = undefined;

/**
 * @member {String} rawUserInfo
 */
URI.prototype.rawUserInfo = undefined;

/**
 * @member {String} scheme
 */
URI.prototype.scheme = undefined;

/**
 * @member {String} schemeSpecificPart
 */
URI.prototype.schemeSpecificPart = undefined;

/**
 * @member {String} userInfo
 */
URI.prototype.userInfo = undefined;


